INSERT INTO public.system_endpoints_conf VALUES ('0a173900885d674d3f8f6128c707cfea', 'FETCH_ROLE_CAPABILITY_ATTRIBUTES', 'aw_core', 'API to fetch role capability attributes', NULL, '{"dev": "http://config-master-service/capability/role/attributes", "prod": "http://config-master-service/capability/role/attributes", "stag": "http://config-master-service/capability/role/attributes"}', 'POST', '{
  "tenantId": "{{tenantId}}",
  "roleIds": {{roleIds}},
  "rolePathSlugs": {{rolePathSlugs}},
  "capabilities": {{capabilities}}
}', NULL, '{"Content-Type": "application/json", "x-claims-sub": "", "x-claims-tenantId": "{{tenantId}}", "x-claims-clientType": "ADMIN"}', 5000, 10000, false, false, false, NULL, NULL, NULL, NULL, NULL, '{"{{roleIds}}": "roleIds", "{{tenantId}}": "tenantId", "{{capabilities}}": "capabilities", "{{rolePathSlugs}}": "rolePathSlugs"}', NULL, true, NULL, '{"qa": {"authorizationType": "NO_AUTH"}, "dev": {"password": "Konnect#123", "username": "airtelWork", "authorizationType": "BASIC_AUTH"}, "prod": {"password": "Konnect#123", "username": "airtelWork", "authorizationType": "BASIC_AUTH"}, "stag": {"password": "Konnect#123", "username": "airtelWork", "authorizationType": "BASIC_AUTH"}}', 1726818609664, 1734527786551, 'Devender', 'Devender', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('10392e57369fad7b8ec40929b7d2d308', 'Create Config Properties', 'aw_core', 'Create Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/create", "prod": "http://{{url}}/{{context}}/property/create", "stag": "http://{{url}}/{{context}}/property/create"}', 'POST', '{
    "operation":{{operation}},
    "properties":{{properties}},
    "propertyTable":"{{propertyTable}}",
    "entityName":"{{entityName}}"
}', NULL, '{"Content-Type": "application/json", "Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, false, false, false, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{operation}}": "operation", "{{entityName}}": "entityName", "{{properties}}": "properties", "{{propertyTable}}": "propertyTable"}', NULL, false, NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013560168, 1724758651706, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('01a502e109092b10738954e4f6414d78', 'Get All and Searched Config Properties', 'aw_core', 'Get All and Searched Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/all", "prod": "http://{{url}}/{{context}}/property/all", "stag": "http://{{url}}/{{context}}/property/all"}', 'GET', NULL, 'startIndex={{startIndex}}&endIndex={{endIndex}}&searchKeyword={{searchKeyword}}&propertyTable={{propertyTable}}&entityName={{entityName}}', '{"Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, false, false, false, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{endIndex}}": "endIndex", "{{entityName}}": "entityName", "{{startIndex}}": "startIndex", "{{propertyTable}}": "propertyTable", "{{searchKeyword}}": "searchKeyword"}', NULL, false, NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013459967, 1724758600457, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('d2d14368553b24346882c13dc8c9ed3f', 'Update Config Properties', 'aw_core', 'Update Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/update", "prod": "http://{{url}}/{{context}}/property/update", "stag": "http://{{url}}/{{context}}/property/update"}', 'POST', '{
    "operation":{{operation}},
    "properties":{{properties}},
    "propertyTable":"{{propertyTable}}",
    "entityName":"{{entityName}}"
}', NULL, '{"Content-Type": "application/json", "Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, false, false, false, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{operation}}": "operation", "{{entityName}}": "entityName", "{{properties}}": "properties", "{{propertyTable}}": "propertyTable"}', NULL, false, NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013597217, 1724758662185, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('0da15ecc9f88f7a25802108db0908a08', 'Delete Config Properties', 'aw_core', 'Delete Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/delete", "prod": "http://{{url}}/{{context}}/property/delete", "stag": "http://{{url}}/{{context}}/property/delete"}', 'POST', '{
    "operation":{{operation}},
    "properties":{{properties}},
    "propertyTable":"{{propertyTable}}",
    "entityName":"{{entityName}}"
}', NULL, '{"Content-Type": "application/json", "Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, false, false, false, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{operation}}": "operation", "{{entityName}}": "entityName", "{{properties}}": "properties", "{{propertyTable}}": "propertyTable"}', NULL, false, NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013642724, 1724758656086, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('10392e57369fad7b8ec40929b7d2z2f3', 'Create Config Properties', 'konnect', 'Create Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/create", "prod": "http://{{url}}/{{context}}/property/create", "stag": "http://{{url}}/{{context}}/property/create"}', 'POST', '{
    "operation":{{operation}},
    "properties":{{properties}},
    "propertyTable":"{{propertyTable}}",
    "entityName":"{{entityName}}"
}', NULL, '{"Content-Type": "application/json", "Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, false, false, false, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{operation}}": "operation", "{{entityName}}": "entityName", "{{properties}}": "properties", "{{propertyTable}}": "propertyTable"}', NULL, false, NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013560168, 1724758651706, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('01a502e109092b10738954e4f6414e88', 'Get All and Searched Config Properties', 'konnect', 'Get All and Searched Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/all", "prod": "http://{{url}}/{{context}}/property/all", "stag": "http://{{url}}/{{context}}/property/all"}', 'GET', NULL, 'startIndex={{startIndex}}&endIndex={{endIndex}}&searchKeyword={{searchKeyword}}&propertyTable={{propertyTable}}&entityName={{entityName}}', '{"Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, false, false, false, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{endIndex}}": "endIndex", "{{entityName}}": "entityName", "{{startIndex}}": "startIndex", "{{propertyTable}}": "propertyTable", "{{searchKeyword}}": "searchKeyword"}', NULL, false, NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013459967, 1724758600457, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('d2d14368553b24346882c13dc8c9ez4f', 'Update Config Properties', 'konnect', 'Update Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/update", "prod": "http://{{url}}/{{context}}/property/update", "stag": "http://{{url}}/{{context}}/property/update"}', 'POST', '{
    "operation":{{operation}},
    "properties":{{properties}},
    "propertyTable":"{{propertyTable}}",
    "entityName":"{{entityName}}"
}', NULL, '{"Content-Type": "application/json", "Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, false, false, false, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{operation}}": "operation", "{{entityName}}": "entityName", "{{properties}}": "properties", "{{propertyTable}}": "propertyTable"}', NULL, false, NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013597217, 1724758662185, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('0da15ecc9f88f7a25802108db0908d98', 'Delete Config Properties', 'konnect', 'Delete Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/delete", "prod": "http://{{url}}/{{context}}/property/delete", "stag": "http://{{url}}/{{context}}/property/delete"}', 'POST', '{
    "operation":{{operation}},
    "properties":{{properties}},
    "propertyTable":"{{propertyTable}}",
    "entityName":"{{entityName}}"
}', NULL, '{"Content-Type": "application/json", "Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, false, false, false, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{operation}}": "operation", "{{entityName}}": "entityName", "{{properties}}": "properties", "{{propertyTable}}": "propertyTable"}', NULL, false, NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013642724, 1724758656086, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('78968ea166b364319127715cbae69f69', 'GET_UNIVERSAL_CAPABILITY_TEMPLATE', 'konnect', 'GET_UNIVERSAL_CAPABILITY_TEMPLATE', NULL, '{"dev": "http://config-master-service/capability/template/v1", "prod": "http://config-master-service/capability/template/v1", "stag": "http://config-master-service/capability/template/v1"}', 'GET', '{
  "tenantId" : "{{tenantId}}",
  "roleCapabilityMappingList" : {{roleCapabilityMappingList}}
}', 'isSubPropertiesRequired={{isSubPropertiesRequired}}', '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 1000, 2000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{tenantId}}": "tenantId", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId", "{{isSubPropertiesRequired}}": "isSubPropertiesRequired", "{{roleCapabilityMappingList}}": "roleCapabilityMappingList"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1735648260491, 1743142950165, 'Devender', 'Devender', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('561fc90238d5616243f81c2ce39df4f2', 'FETCH_SAVED_CAPABILITY_ROLE', 'konnect', 'FETCH_SAVED_CAPABILITY_ROLE', NULL, '{"dev": "http://config-master-service/capability/fetch/saved/role", "prod": "http://config-master-service/capability/fetch/saved/role", "stag": "http://config-master-service/capability/fetch/saved/role"}', 'GET', '{
  "tenantId" : "{{tenantId}}",
  "roleCapabilityMappingList" : {{roleCapabilityMappingList}}
}', 'tenantId={{tenantId}}&&organisationId={{organisationId}}&&roleId={{roleId}}', '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 1000, 2000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{roleId}}": "roleId", "{{tenantId}}": "tenantId", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{organisationId}}": "organisationId", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId", "{{roleCapabilityMappingList}}": "roleCapabilityMappingList"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1735657877758, 1743143029193, 'Devender', 'Devender', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('49d38ee6aa8c820f1e1dc5710ec9164b', 'FETCH_ALL_ROLES_IN_ORGANISATION_TREE_TRANSFORMATION', 'konnect', 'FETCH_ALL_ROLES_IN_ORGANISATION_TREE_TRANSFORMATION', NULL, '{"dev": "http://skeletor-service/skeletor-service/role/all/", "prod": "http://skeletor-service/skeletor-service/role/all/", "stag": "http://skeletor-service/skeletor-service/role/all/"}', 'GET', NULL, 'organisationId={{organisationId}}&tenantId={{tenantId}}', '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{tenantId}}": "tenantId", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{organisationId}}": "organisationId", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1728287245055, 1760332916809, 'ASHISH AGGARWAL', 'Akshansh', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('feb5f68ebfd0dde50121a63eba54d538', 'UPDATE_CAPABILITY_FOR_ROLES', 'konnect', 'UPDATE_CAPABILITY_FOR_ROLES', NULL, '{"dev": "http://config-master-service/capability/update/roles", "prod": "http://config-master-service/capability/update/roles", "stag": "http://config-master-service/capability/update/roles"}', 'POST', '{
  "capabilityEventDTO" : {{capabilityEventDTO}},
  "childRoleIdList" : {{childRoleIdList}}
}', NULL, '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 1000, 5000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{childRoleIdList}}": "childRoleIdList", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{capabilityEventDTO}}": "capabilityEventDTO", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1735659919923, 1743143085916, 'Devender', 'Devender', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('d525ded5a05331264508a4efe188504d', 'Refresh Capability Cache in Microservice', 'konnect', 'Common api to refresh capability cache in microservice', NULL, '{"dev": "http://{{url}}/capability/refresh/cache", "prod": "http://{{url}}/capability/refresh/cache", "stag": "http://{{url}}/capability/refresh/cache"}', 'POST', '{
    "rolePathSlugList":{{rolePathSlugList}}
}', '', '{"Content-Type": "application/json", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{rolePathSlugList}}": "rolePathSlugList", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1746528361765, 1746528361765, 'Airtel Work', 'Airtel Work', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('727e7a7ad17224d74cb42f757edd1984', 'rule_pad_config_get_all_filters', 'konnect', 'rule_pad_config_get_all_filters', NULL, '{"dev": "http://{{url}}/rulepad/v1/filters/{{process}}", "prod": "http://{{url}}/rulepad/v1/filters/{{process}}", "stag": "http://{{url}}/rulepad/v1/filters/{{process}}"}', 'GET', NULL, '', '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 500, 1000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{process}}": "process", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1740993378816, 1743157874337, 'ASHISH AGGARWAL', 'ASHISH AGGARWAL', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('47eb994c1341deb8e014119d60f51858', 'rule_pad_config_get_and_search', 'konnect', 'rule_pad_config_get_and_search', NULL, '{"dev": "http://{{url}}/rulepad/v1/rules/all", "prod": "http://{{url}}/rulepad/v1/rules/all", "stag": "http://{{url}}/rulepad/v1/rules/all"}', 'POST', '{
    "role":"{{role}}",
    "fileType":"{{fileType}}",
    "process":"{{process}}",
    "startIndex":"{{startIndex}}",
    "endIndex":"{{endIndex}}",
    "searchKey":"{{searchKey}}"
}', NULL, '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-claims-uid": "{{x-uid}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{role}}": "role", "{{x-uid}}": "x-uid", "{{process}}": "process", "{{endIndex}}": "endIndex", "{{fileType}}": "fileType", "{{searchKey}}": "searchKey", "{{startIndex}}": "startIndex", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1741071604701, 1746095725772, 'ASHISH AGGARWAL', 'ASHISH AGGARWAL', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('13b955a04ef08445a6127fb45eac139e', 'rule_pad_config_update', 'konnect', 'rule_pad_config_update', NULL, '{"dev": "http://{{url}}/rulepad/v1/rules/update", "prod": "http://{{url}}/rulepad/v1/rules/update", "stag": "http://{{url}}/rulepad/v1/rules/update"}', 'PUT', '{
    "fileType":"{{fileType}}",
    "role":"{{role}}",
    "process":"{{process}}",
    "properties":{{properties}},
    "header":{{header}}
}', NULL, '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{role}}": "role", "{{header}}": "header", "{{process}}": "process", "{{fileType}}": "fileType", "{{properties}}": "properties", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1741093005913, 1743618487267, 'ASHISH AGGARWAL', 'ASHISH AGGARWAL', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('d25cdc03186b6535153661e866ee59a2', 'rule_pad_config_create', 'konnect', 'rule_pad_config_create', NULL, '{"dev": "http://{{url}}/rulepad/v1/rules/create", "prod": "http://{{url}}/rulepad/v1/rules/create", "stag": "http://{{url}}/rulepad/v1/rules/create"}', 'POST', '{
    "fileType":"{{fileType}}",
    "role":"{{role}}",
    "process":"{{process}}",
    "properties":{{properties}},
    "header":{{header}}
}', NULL, '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{role}}": "role", "{{header}}": "header", "{{process}}": "process", "{{fileType}}": "fileType", "{{properties}}": "properties", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1741086514979, 1743618546032, 'ASHISH AGGARWAL', 'ASHISH AGGARWAL', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('f9c210942dde2b8fd00981a419ea5163', 'rule_pad_config_delete', 'konnect', 'rule_pad_config_delete', NULL, '{"dev": "http://{{url}}/rulepad/v1/rules/delete", "prod": "http://{{url}}/rulepad/v1/rules/delete", "stag": "http://{{url}}/rulepad/v1/rules/delete"}', 'POST', '{
    "fileType":"{{fileType}}",
    "role":"{{role}}",
    "process":"{{process}}",
    "properties":{{properties}},
    "header":{{header}}
}', NULL, '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{role}}": "role", "{{header}}": "header", "{{process}}": "process", "{{fileType}}": "fileType", "{{properties}}": "properties", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1741093031749, 1743618449835, 'ASHISH AGGARWAL', 'ASHISH AGGARWAL', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('1646398b13dbfca8050e794a7d4c72f1', 'rule_pad_config_view_rule_history', 'konnect', 'rule_pad_config_view_rule_history', NULL, '{"dev": "http://{{url}}/rulepad/v1/rule/history", "prod": "http://{{url}}/rulepad/v1/rule/history", "stag": "http://{{url}}/rulepad/v1/rule/history"}', 'POST', '{
    "role":"{{role}}",
    "fileType":"{{fileType}}",
    "process":"{{process}}",
    "startIndex":"{{startIndex}}",
    "endIndex":"{{endIndex}}",
    "ruleName":"{{ruleName}}"
    
}', NULL, '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-claims-uid": "{{x-claims-uid}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{role}}": "role", "{{process}}": "process", "{{endIndex}}": "endIndex", "{{fileType}}": "fileType", "{{ruleName}}": "ruleName", "{{startIndex}}": "startIndex", "{{x-claims-sub}}": "x-claims-sub", "{{x-claims-uid}}": "x-claims-uid", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1744229702550, 1744230970815, 'ASHISH AGGARWAL', 'ASHISH AGGARWAL', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('8e533b4457ab80032d0d18249386f6ae', 'rule_pad_config_rollback_rule', 'konnect', 'rule_pad_config_rollback_rule', NULL, '{"dev": "http://{{url}}/rulepad/v1/rule/rollback/{{rollbackId}}", "prod": "http://{{url}}/rulepad/v1/rule/rollback/{{rollbackId}}", "stag": "http://{{url}}/rulepad/v1/rule/rollback/{{rollbackId}}"}', 'PUT', '{
    "process":{{process}}
}', NULL, '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-claims-uid": "{{x-claims-uid}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{process}}": "process", "{{rollbackId}}": "rollbackId", "{{x-claims-sub}}": "x-claims-sub", "{{x-claims-uid}}": "x-claims-uid", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1744229855760, 1746085369708, 'ASHISH AGGARWAL', 'ASHISH AGGARWAL', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('0786b763dc315b7a1c4445d81f03729f', 'GET_COLUMN_MAPPING_FETCH_CONTEXT_API', 'konnect', NULL, NULL, '{"dev": "http://skeletor-service/skeletor-service/organisation/context/details", "prod": "http://skeletor-service/skeletor-service/organisation/context/details", "stag": "http://skeletor-service/skeletor-service/organisation/context/details"}', 'POST', '{
"process":"{{process}}",
"tenantId":"{{tenantId}}"
}
', 'tenantId={{tenantId}}', '{}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{process}}": "process", "{{tenantId}}": "tenantId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1683109332504, 1760332823798, 'Dhruv', 'Akshansh', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('b97d2a2dd920c48b1d945b4b16cac531', 'UPDATE_LOGIN_FOR_CAPABILITY_CACHING', 'konnect', 'UPDATE_LOGIN_FOR_CAPABILITY_CACHING', NULL, '{"dev": "http://login-manager-service/role-capability/update/endpoints", "prod": "http://login-manager-service/role-capability/update/endpoints", "stag": "http://login-manager-service/role-capability/update/endpoints"}', 'POST', '{
  "tenantId" : "{{tenantId}}",
  "roleCapabilityMappingList" : {{roleCapabilityMappingList}}
}', NULL, '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{tenantId}}": "tenantId", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId", "{{roleCapabilityMappingList}}": "roleCapabilityMappingList"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1735209319873, 1752049433767, 'Devender', 'Akshansh', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('c994c0ad6e4d7529ef0e55ff19f2fd6f', 'SKELETOR_USER_PROCESS_AND_ROLE_DETAILS_TRANSFORMATION', 'aw_core', 'API to populate APP listing for USER While Login', NULL, '{"dev": "http://skeletor-service/skeletor-service/user/get-processes-and-roles", "prod": "http://skeletor-service/skeletor-service/user/get-processes-and-roles", "stag": "http://skeletor-service/skeletor-service/user/get-processes-and-roles"}', 'GET', NULL, 'idType={{idType}}&idValue={{idValue}}', '{"Content-Type": "application/json", "x-claims-sub": "", "x-claims-clientType": "ADMIN"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{idType}}": "idType", "{{idValue}}": "idValue"}', NULL, true, NULL, '{"qa": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "dev": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1717153849538, 1759729764751, 'Riju Tejas Singh', 'Akshansh', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "6", "slidingWindowType": "TIME_BASED", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "11", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "1", "permittedNumberOfCallsInHalfOpenState": "2"}', NULL, '{"count": 1, "delay": 8800, "enabled": true, "callbackBeanName": "okok"}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('b6bb04033037d9215116294a5493cba8', 'FETCH_FILTERED_ROLES_BY_SKELETOR', 'konnect', 'FETCH_FILTERED_ROLES_BY_SKELETOR', NULL, '{"dev": "http://skeletor-service/skeletor-service/role/v2/filter", "prod": "http://skeletor-service/skeletor-service/role/v2/filter", "stag": "http://skeletor-service/skeletor-service/role/v2/filter"}', 'POST', '{
  "filters": {{filters}}
}', 'tenantId={{tenantId}}', '{"Content-Type": "application/json", "x-claims-sub": "{{x-claims-sub}}", "x-active-role": "{{x-active-role}}", "x-claims-roles": "{{x-claims-roles}}", "x-claims-userId": "{{x-claims-userId}}", "x-claims-tenantId": "{{x-claims-tenantId}}", "x-claims-clientType": "{{x-claims-clientType}}", "X-AirtelWork-RequestId": "{{X-AirtelWork-RequestId}}"}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{"{{filters}}": "filters", "{{tenantId}}": "tenantId", "{{x-claims-sub}}": "x-claims-sub", "{{x-active-role}}": "x-active-role", "{{x-claims-roles}}": "x-claims-roles", "{{x-claims-userId}}": "x-claims-userId", "{{x-claims-tenantId}}": "x-claims-tenantId", "{{x-claims-clientType}}": "x-claims-clientType", "{{X-AirtelWork-RequestId}}": "X-AirtelWork-RequestId"}', NULL, NULL, NULL, '{"dev": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": "Konnect#123", "username": "airtelWork", "onlineSecretKey": null, "authorizationType": "BASIC_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1730289848277, 1760329151347, 'ASHISH AGGARWAL', 'Akshansh', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);
INSERT INTO public.system_endpoints_conf VALUES ('21e104edc03ff0281680bb4fabccd50f', 'LOCALE_DATA_API', 'konnect', NULL, NULL, '{"dev": "http://config-master-service/translations/fetch/all", "prod": "http://config-master-service/translations/fetch/all", "stag": "http://config-master-service/translations/fetch/all"}', 'GET', NULL, NULL, '{}', 5000, 10000, false, false, NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, NULL, NULL, '{"dev": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "prod": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}, "stag": {"token": null, "password": null, "username": null, "onlineSecretKey": null, "authorizationType": "NO_AUTH", "myAirtelAppSecret": null, "onlineRequesterId": null, "myAirtelAppVersion": null}}', 1760438518755, 1760440074165, 'Akshansh', 'Akshansh', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', false, '{"count": null, "delay": null, "enabled": null, "callbackBeanName": null}', NULL);

INSERT INTO "public"."system_endpoints_conf" ("id", "system_name", "client_name", "description", "api_endpoint", "api_endpoints_map", "request_method", "payload", "query_params", "request_headers", "connection_timeout", "socket_timeout", "use_cache", "use_proxy", "is_proxy_secure", "proxy_host", "proxy_port", "proxy_user", "proxy_password", "cache_key_info", "placeholders_map", "placeholders", "published", "api_security_param", "api_security_param_map", "created_at", "updated_at", "created_user", "modified_user", "version", "api_circuit_breaker_param", "print_response", "retry_config", "api_retry_param") VALUES
('01a502e109092b10738954e4f6414d72', 'B2B Acquisition Get All and Searched Config Properties', 'konnect', 'B2B Acquisition Get All and Searched Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/all", "prod": "http://{{url}}/{{context}}/property/all", "stag": "http://{{url}}/{{context}}/property/all"}', 'GET', NULL, 'startIndex={{startIndex}}&endIndex={{endIndex}}&searchKeyword={{searchKeyword}}&propertyTable={{propertyTable}}&entityName={{entityName}}', '{"Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, 'f', 'f', 'f', NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{endIndex}}": "endIndex", "{{entityName}}": "entityName", "{{startIndex}}": "startIndex", "{{propertyTable}}": "propertyTable", "{{searchKeyword}}": "searchKeyword"}', NULL, 'f', NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013459967, 1724758600457, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', 'f', '{}', NULL),
('10392e57369fad7b8ec40929b7d2d302', 'B2B Acquisition Create Config Properties', 'konnect', 'B2B Acquisition Create Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/create", "prod": "http://{{url}}/{{context}}/property/create", "stag": "http://{{url}}/{{context}}/property/create"}', 'POST', '{
"operation":{{operation}},
"properties":{{properties}},
"propertyTable":"{{propertyTable}}",
"entityName":"{{entityName}}"
}', NULL, '{"Content-Type": "application/json", "Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, 'f', 'f', 'f', NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{operation}}": "operation", "{{entityName}}": "entityName", "{{properties}}": "properties", "{{propertyTable}}": "propertyTable"}', NULL, 'f', NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013560168, 1724758651706, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', 'f', '{}', NULL),
('d2d14368553b24346882c13dc8c9ed2f', 'B2B Acquisition Update Config Properties', 'konnect', 'B2B Acquisition Update Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/update", "prod": "http://{{url}}/{{context}}/property/update", "stag": "http://{{url}}/{{context}}/property/update"}', 'POST', '{
"operation":{{operation}},
"properties":{{properties}},
"propertyTable":"{{propertyTable}}",
"entityName":"{{entityName}}"
}', NULL, '{"Content-Type": "application/json", "Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, 'f', 'f', 'f', NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{operation}}": "operation", "{{entityName}}": "entityName", "{{properties}}": "properties", "{{propertyTable}}": "propertyTable"}', NULL, 'f', NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013597217, 1724758662185, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', 'f', '{}', NULL),
('0da15ecc9f88f7a25802108db0908a02', 'B2B Acquisition Delete Config Properties', 'konnect', 'B2B Acquisition Delete Config Properties', NULL, '{"dev": "http://{{url}}/{{context}}/property/delete", "prod": "http://{{url}}/{{context}}/property/delete", "stag": "http://{{url}}/{{context}}/property/delete"}', 'POST', '{
"operation":{{operation}},
"properties":{{properties}},
"propertyTable":"{{propertyTable}}",
"entityName":"{{entityName}}"
}', NULL, '{"Content-Type": "application/json", "Authorization": "Basic YWlydGVsV29yazpLb25uZWN0IzEyMw=="}', 5000, 10000, 'f', 'f', 'f', NULL, NULL, NULL, NULL, NULL, '{"{{url}}": "url", "{{context}}": "context", "{{operation}}": "operation", "{{entityName}}": "entityName", "{{properties}}": "properties", "{{propertyTable}}": "propertyTable"}', NULL, 'f', NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1676013642724, 1724758656086, 'Dhruv', 'Ananay', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', 'f', '{}', NULL),
('7048c7b2717e44e0b1430fd7e3d94292', 'B2B Acquisition Get Filtered Recommended Products', 'konnect', 'Get recommended products from master data rules', NULL, '{"dev": "http://tenant-service/master/data/filter", "prod": "http://tenant-service/master/data/filter", "stag": "http://tenant-service/master/data/filter"}', 'POST', '{
"filters": [
{
"key": "industry_type",
"value": "{{industry_type}}",
"category": "task",
"operator": "equal",
"taskList": "commonDetails.industry",
"joinCondition": "and"
},
{
"key": "number_of_employees_l",
"value": "{{number_of_employees}}",
"category": "task",
"operator": "is less than equals to",
"taskList": "commonDetails.number_of_employees",
"joinCondition": "and"
},
{
"key": "number_of_employees_r",
"value": "{{number_of_employees}}",
"category": "task",
"operator": "is greater than",
"taskList": "commonDetails.number_of_employees",
"joinCondition": "and"
},
{
"key": "number_of_locations_l",
"value": "{{number_of_locations}}",
"category": "task",
"operator": "is less than equals to",
"taskList": "commonDetails.number_of_locations",
"joinCondition": "and"
},
{
"key": "number_of_locations_r",
"value": "{{number_of_locations}}",
"category": "task",
"operator": "is greater than",
"taskList": "commonDetails.number_of_locations",
"joinCondition": "or"
},
{
"key": "number_of_cocp_connections_l",
"value": "{{number_of_cocp_connections}}",
"category": "task",
"operator": "is less than",
"taskList": "commonDetails.number_of_households",
"joinCondition": "and"
},
{
"key": "number_of_cocp_connections_r",
"value": "{{number_of_cocp_connections}}",
"category": "task",
"operator": "is greater than",
"taskList": "commonDetails.number_of_households",
"joinCondition": ""
}
],
"selectedColumns": [
"recommended_product"
]
}', 'tableId={{tableId}}&isProcessedOutput=true', '{"Content-Type": "application/json", "x-claims-roles": "AIRTEL:ADMIN", "x-claims-userId": "19b1c23a-29d4-4136-92db-af39a7018fdb", "x-claims-tenantId": "f115f23c-3a95-4cc8-8e3e-6e5907300c49", "x-claims-clientType": "ADMIN"}', 5000, 10000, 'f', 'f', 'f', NULL, NULL, NULL, NULL, NULL, '{"{{tableId}}": "tableId", "{{industry_type}}": "industry_type", "{{number_of_employees}}": "number_of_employees", "{{number_of_locations}}": "number_of_locations", "{{number_of_cocp_connections}}": "number_of_cocp_connections"}', NULL, NULL, NULL, '{"dev": {"authorizationType": "NO_AUTH"}, "prod": {"authorizationType": "NO_AUTH"}, "stag": {"authorizationType": "NO_AUTH"}}', 1681468912397, 1684467362735, 'Dhruv', 'Dhruv', NULL, '{"ignoreExceptions": [], "recordExceptions": [], "slidingWindowSize": "5", "slidingWindowType": "", "failureRateThreshold": "50", "minimumNumberOfCalls": "5", "slowCallRateThreshold": "100", "waitDurationInOpenState": "10", "slowCallDurationThreshold": "1", "maxWaitDurationInHalfOpenState": "0", "permittedNumberOfCallsInHalfOpenState": "2"}', NULL, NULL, NULL);